### ISSUE TITLE
Setup Chromatic CI/CD

### ISSUE THREAD

**Issue by sukrutsathaye** [ai-app-factory/ng-mono#6]
We want to set up Chromatic CI/CD as per [docs](https://www.chromatic.com/docs/github-actions/) to avoid manual publishing to Chromatic. 

We need to grab the project tokens from the Chromatic console and add them to the repository secrets to be used from CI file by specifying just the name of the project.

**Comment by sukrutsathaye** [comment]
```yaml
name: "Chromatic"

on:
  push:
    branches:
      - libs/refined-mui-lib # Only run on library changes
    paths-ignore:
      - 'libs/**/src/**/*.spec.ts'
      - 'libs/**/src/**/*.spec.tsx'

jobs:
  chromatic:
    runs-on: ubuntu-latest
    name: Run Chromatic
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: yarn install

      - name: Build Refined Mui Lib Storybook
        run: yarn nx run refined-mui-lib:build-storybook

      - name: Publish Refined Mui Lib to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_REFINED_MUI_LIB }}
          workingDir: libs/refined-mui-lib
          storybookBuildDir:  /home/runner/work/ng-mono/ng-mono/dist/storybook/refined-mui-lib
```
